apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kobj
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kobj
